APEX Workflow LiveLab WMS ID:11525
oracle-livelabs/apex pull request #122
Opened 2023-12-13 16:17 UTC by tomohamm

# Add here your WMS ID - 11525

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [Y] All filenames are lower case (including folders, images, files, etc.)
- [Y] Filenames are descriptive
- [Y]Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [N] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [Y] Image references in markdown contain an alternate text

2023-12-15 11:22 UTC, KillianLynch requested changes
Hi @tomohamm - the markdown file structure of the PR needs to follow the LiveLabs standard format. Please refer to the QA guide in [WMS](https://apex.oraclecorp.com/pls/apex/f?p=24885:320:109037984706701::::P320_ID:11525)

2023-12-19 17:25 UTC, hope-fisher commented
Hi @tomohamm as Killian mentioned, the folder structure needs to be adjusted. Under folder "apex-workflows", each lab should have its own subfolder. Each of those lab folders will contain an images folder (for the images used only in that lab) and the relevant .md file. 

Also, your manifest needs to contain a help line, so that users can contact the correct support when needed. It would look like this: 

```
    "workshoptitle": "Simplify Business Process Management Using APEX Workflow",
    "help": "livelabs-help-apex_us@oracle.com",
    "tutorials": [
```

Lab 4 of [this Guide](https://oracle-livelabs.github.io/common/sample-livelabs-templates/create-labs/labs/workshops/livelabs/?lab=4-labs-markdown-develop-content) may be helpful.

2024-01-02 20:19 UTC, ramumg reviewed
Hi @tomohamm, 

please make sure you follow the QA doc for the image naming:
![image](https://github.com/oracle-livelabs/apex/assets/84869754/e8c39343-db83-4cd5-b5a1-71c59d85a12d)
the naming has to be more descriptive.

Thank you!

2024-01-03 17:11 UTC, denisemyrick requested changes

2024-01-05 15:03 UTC, denisemyrick approved these changes

2024-01-05 15:03 UTC, merged