HOL 7 Update. WMS ID: 11155
oracle-livelabs/apex pull request #139
Opened 2024-02-08 17:36 UTC by tomohamm

# WMS ID: 11155

# General requirements
1. Information in the workshop is adequate and updated
2. Code is correct and working
3. Links are correct
4. Make sure you enter the help email link in your manifest.json
5. Please make sure WMS URLs are updated as needed after your PR is approved

# Checklist - Refer to the QA document for the complete list 
Please confirm that the following is completed before submitting your PR

- [ ] All filenames are lower case (including folders, images, files, etc.)
- [ ] Filenames are descriptive
- [ ] Your workshop folder structure should be similar to the one used in the sample workshop (https://github.com/oracle-livelabs/common/tree/main/sample-livelabs-templates/sample-workshop)
- [ ] Are you using multiple versions (desktop/, sandbox/, tenancy/)? Make sure that each of them contains a manifest.json and an index.html
- [ ] Image references in markdown contain an alternate text

2024-02-08 17:37 UTC, tomohamm commented
@hope-fisher Please review.

2024-02-08 17:48 UTC, hope-fisher commented
@tomohamm please have the workshop owner add you as a part of the workshop team so that this and future PRs can be approved.

2024-02-08 18:50 UTC, tomohamm commented
@hope-fisher I am added to the workshop team now. Please check.

2024-02-10 06:17 UTC, hope-fisher requested changes
all files must be in lowercase. Please update `apex-professional-hol7/images/Screenshot 2023-10-12 at 1.01.01 AM.png` accordingly.

2024-02-12 12:43 UTC, dannymgithub requested changes
Just flagging that Lab1 appears twice below, in the event it causes issues due to duplication.

2024-02-12 12:43 UTC, dannymgithub commented on apex-professional-hol7/workshops/tenancy/manifest.json
Just flagging that Lab1 appears twice below, in the event it causes issues due to duplication.

2024-02-12 13:22 UTC, dannymgithub approved these changes

2024-02-12 13:23 UTC, dannymgithub approved these changes

2024-02-12 13:24 UTC, merged